#!/usr/bin/env python3
VERSION = 'v1.0'
# ---------------------------------------------------------------------------------------------
# build_worklist.py - regenerate the graphics work list from svg_layout_audit, reproducibly.
#
# WHY THIS EXISTS. GPT_WORKLIST_S99.md was assembled by hand. That is why, when S101 came to
# doubt its ordering, nobody could re-derive it - there was nothing to re-run. A list that
# orders somebody else's work has to be a GENERATE, not a transcript, or it silently ages into
# a set of instructions nobody can check. The graphics chat works from this file; a stale
# ordering there costs real hours on the wrong graphic.
#
# WHAT IT ORDERS BY. Worst overflow first, in user units, as measured by svg_layout_audit.
# That number was WRONG for every file whose type is styled by CSS until svg_layout_audit v1.17
# taught the tool to read <style> and style="" - before that, 371 of 2,469 labels were measured
# at 16px whatever their real size, and the ordering inherited every one of those errors.
# ANY worklist generated by a version below v1.18 should be discarded rather than trusted.
#
# WHAT IT LEAVES OUT, and why that is a judgement recorded rather than a rule invented:
# the S99 list's own preamble drew the line at "fixed locally" - plain href, dead alpha,
# designer font stacks and files over the gate 37 ceiling are repaired by svg_layout_audit,
# flatten_alpha and fit_raster_svg without anyone redrawing anything. Those are still excluded
# here, and they are COUNTED and REPORTED rather than dropped, so the local-fix backlog stays
# visible instead of vanishing into a filter.
#
# ENTRYPOINT IS build(images_dir) -> (worklist, local). There is no main() worth calling.
#
# CHANGELOG
# v1.0 (S102): first version. Replaces the hand-assembled GPT_WORKLIST_S99.md.
# ---------------------------------------------------------------------------------------------

import sys, os, re, glob, tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import svg_layout_audit as SLA

MIN_AUDIT_VERSION = (1, 18)

# A finding belongs to the LOCAL pile only if a tool in this repo repairs it without a redraw.
# Matched on stable leading phrases, not on whole sentences, so wording edits upstream do not
# silently re-route a whole category.
LOCAL_PATTERNS = (
    '<image> uses a plain href',
    'carries a fully-opaque alpha channel',
    'font stack leads with',
    "over gate 37's",
    'over gate 3',                 # the ceiling message carries the gate number inline
)


def _is_local(finding):
    return any(p in finding for p in LOCAL_PATTERNS)


def _overflow(finding):
    """Units of overflow in a finding, or 0.0 if it is not an overflow finding."""
    m = re.match(r'text overflows its panel by ([\d.]+) units', finding)
    return float(m.group(1)) if m else 0.0


def _audit_version_ok():
    m = re.match(r'v(\d+)\.(\d+)', SLA.VERSION)
    return bool(m) and (int(m.group(1)), int(m.group(2))) >= MIN_AUDIT_VERSION


def build(images_dir='images'):
    """Return (worklist, local).

    worklist: list of (filename, worst_overflow, [findings]) sorted worst-first.
    local:    dict filename -> [findings] for the mechanically-fixable pile.
    """
    worklist, local = [], {}
    for path in sorted(glob.glob(os.path.join(images_dir, '*.svg'))):
        name = os.path.basename(path)
        try:
            findings = SLA.audit(path)
        except Exception as exc:                       # a crash is not a clean file
            worklist.append((name, float('inf'), [f'AUDIT CRASHED: {exc}']))
            continue
        human = [f for f in findings if not _is_local(f)]
        mech = [f for f in findings if _is_local(f)]
        if mech:
            local[name] = mech
        if human:
            worklist.append((name, max(_overflow(f) for f in human), human))
    # worst overflow first; then most findings; then name, so the order is total and stable
    worklist.sort(key=lambda r: (-r[1], -len(r[2]), r[0]))
    return worklist, local


def render(worklist, local, session):
    L = []
    A = L.append
    n_over = sum(1 for _n, w, _f in worklist if w > 0)
    A(f'# GPT graphics work list — S{session} (generated)')
    A('')
    A(f'**{len(worklist)} files** needing a human, from an audit of all SVGs in `images/`.')
    A('Worst-first by how far text runs outside its panel.')
    A('')
    A(f'Generated by `build_worklist.py {VERSION}` against `svg_layout_audit {SLA.VERSION}`.')
    A('**Do not hand-edit — regenerate.** Any list built against an audit below v1.18 was')
    A('ordered by font sizes the tool could not read and should be discarded.')
    A('')
    A('Mechanical defects are NOT here — plain `href`, dead alpha, designer font stacks and')
    A('files over the gate 37 ceiling are fixed locally by `svg_layout_audit`, `flatten_alpha`')
    A('and `fit_raster_svg`. They are listed at the end so the backlog stays visible.')
    A('')
    A('Send one file at a time. Attach the SVG, paste its block, bring the result back before')
    A('moving on.')
    A('')
    A(f'{n_over} of these {len(worklist)} have text outside a panel; the rest are structural.')
    A('')
    for name, worst, findings in worklist:
        A(f'## {name}')
        if worst > 0:
            A(f'*worst overflow: {worst:.0f} units*')
        A('')
        for f in findings:
            A(f'- {f}')
        A('')
    A('---')
    A('')
    A('## Local-fix backlog (no redraw needed)')
    A('')
    if not local:
        A('_None._')
    else:
        A(f'{sum(len(v) for v in local.values())} findings across {len(local)} files.')
        A('')
        for name in sorted(local):
            A(f'- **{name}** — ' + '; '.join(f.split(' - ')[0].split('.')[0]
                                             for f in local[name]))
    A('')
    return '\n'.join(L) + '\n'


def _selftest():
    """Controls in both directions: silent on clean, loud on seeded, and ORDER is tested.

    Ordering is the whole product here, so a control that only proves 'a defect appears' would
    not be evidence for the thing this file is for (§24.8).
    """
    ok = True

    def svg(body, style=''):
        st = f'<style>{style}</style>' if style else ''
        return ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1100 850">'
                f'{st}<rect x="40" y="40" width="600" height="200" fill="#fff"/>{body}</svg>')

    with tempfile.TemporaryDirectory() as d:
        def put(name, content):
            with open(os.path.join(d, name), 'w', encoding='utf-8') as fh:
                fh.write(content)

        # CONTROL A - a clean file must not appear at all
        put('a_clean.svg', svg('<text x="60" y="120" font-size="12" '
                               'font-family="Arial, Helvetica, sans-serif">short</text>'))
        wl, _lo = build(d)
        if any(n == 'a_clean.svg' for n, _w, _f in wl):
            print('   FAIL  CONTROL A: a clean file appeared in the worklist')
            ok = False
        else:
            print('   OK    CONTROL A: clean file is absent')

        # CONTROL B - two seeded overflows must be ordered WORSE FIRST
        long_s = 'x' * 200
        put('b_small.svg', svg(f'<text x="600" y="120" font-size="12" '
                               f'font-family="Arial, Helvetica, sans-serif">{"y"*6}</text>'))
        put('c_big.svg', svg(f'<text x="600" y="120" font-size="28" '
                             f'font-family="Arial, Helvetica, sans-serif">{long_s}</text>'))
        wl, _lo = build(d)
        names = [n for n, _w, _f in wl]
        if 'c_big.svg' not in names or 'b_small.svg' not in names:
            print(f'   FAIL  CONTROL B: seeded overflow missing ({names})')
            ok = False
        elif names.index('c_big.svg') > names.index('b_small.svg'):
            print('   FAIL  CONTROL B: the WORSE overflow was not ordered first')
            ok = False
        else:
            print('   OK    CONTROL B: worse overflow ordered first')

        # CONTROL C - a CSS-declared font-size must drive the ordering. This is the S102 bug:
        # with the size read as 16 instead of 40 the file sorts far too low.
        put('d_css.svg', svg('<text x="600" y="120" class="big" '
                             f'font-family="Arial, Helvetica, sans-serif">{"z"*60}</text>',
                             style='.big{font-size:40px}'))
        wl, _lo = build(d)
        row = [r for r in wl if r[0] == 'd_css.svg']
        if not row:
            print('   FAIL  CONTROL C: CSS-sized overflow not detected at all')
            ok = False
        elif row[0][1] < 500:
            print(f'   FAIL  CONTROL C: CSS size ignored - overflow read as {row[0][1]:.0f}')
            ok = False
        else:
            print(f'   OK    CONTROL C: CSS font-size drives the measure ({row[0][1]:.0f} units)')

        # CONTROL D - a mechanical-only defect is EXCLUDED from the worklist and COUNTED locally
        put('e_mech.svg', svg('<text x="60" y="120" font-size="12" '
                              'font-family="Papyrus, fantasy">short</text>'))
        wl, lo = build(d)
        in_wl = any(n == 'e_mech.svg' for n, _w, _f in wl)
        in_lo = 'e_mech.svg' in lo
        if in_wl or not in_lo:
            print(f'   FAIL  CONTROL D: mechanical defect routed wrong '
                  f'(worklist={in_wl}, local={in_lo})')
            ok = False
        else:
            print('   OK    CONTROL D: mechanical defect excluded, and counted in local pile')

        # CONTROL E - the audit version guard must actually be able to fail
        real = SLA.VERSION
        try:
            SLA.VERSION = 'v1.17'
            stale_ok = _audit_version_ok()
            SLA.VERSION = 'v1.18'
            fresh_ok = _audit_version_ok()
        finally:
            SLA.VERSION = real
        if stale_ok or not fresh_ok:
            print(f'   FAIL  CONTROL E: version guard cannot distinguish a stale audit from a current one')
            ok = False
        else:
            print('   OK    CONTROL E: version guard rejects a stale audit')

    print()
    print('ALL CONTROLS PASS - order is tested, not just presence.' if ok
          else 'CONTROLS FAILED.')
    return ok


if __name__ == '__main__':
    if '--selftest' in sys.argv:
        sys.exit(0 if _selftest() else 1)
    if not _audit_version_ok():
        sys.exit(f'svg_layout_audit is {SLA.VERSION}; this generator requires v1.18 or newer, '
                 f'because earlier versions could not read a font-size out of CSS and every '
                 f'ordering they produced inherited that error.')
    session = '102'
    for i, a in enumerate(sys.argv):
        if a == '--session' and i + 1 < len(sys.argv):
            session = sys.argv[i + 1]
    wl, lo = build('images')
    out = render(wl, lo, session)
    dest = f'GPT_WORKLIST_S{session}.md'
    tmp = dest + '.tmp'
    with open(tmp, 'w', encoding='utf-8') as fh:
        fh.write(out)
    os.replace(tmp, dest)
    print(f'build_worklist {VERSION}  (svg_layout_audit {SLA.VERSION})')
    print(f'  wrote {dest}: {len(wl)} files needing a human, '
          f'{sum(len(v) for v in lo.values())} local-fix findings across {len(lo)} files')
