#!/usr/bin/env python3
"""next_pointer.py v1.1 - the end-of-lesson forward link (Bible §3.1a).

Generates ONE byte-identical-by-construction block per lesson and seats it
immediately before the §5b footer paragraph, which is the last element on the
page and the only seat present in all sixteen lessons.

Entrypoint trap (§24 house rule): the real entrypoint is build(dir), NOT main().

Design constraints, each of them load-bearing:
  * Every class used already exists in css/book.css, so applying this does NOT
    move the stylesheet and §27.8b's three-step sequence never runs.
  * No inline style="" is emitted (§27.12).
  * The href and the id both resolve, so §27.14 stays green.
  * Lesson titles are DERIVED from the lesson strip, never typed (§24.10).

    THE APOSTROPHE IS RULED (DJ ruling B, S123) and esc() no longer transforms it, so
    the titles this tool emits are byte-faithful copies of the strip's. The note that
    stood here from v1.0.1 to v1.0.2 described the defect; it is closed, and the one
    character it affected - L11's "Time Lies, Distance Doesn't" in Lesson_10.html -
    now matches the 21 other places the book spells that title.
  * L16 gets no block: it is the last lesson and is entitled to none (§3.1).

Usage:
    python3 next_pointer.py --selftest
    python3 next_pointer.py --check        # exit 1 if any lesson is missing it
    python3 next_pointer.py --apply
"""

import glob
import html
import os
import re
import sys

# VERSION below is the ONE home read by session_versions. It sits ABOVE the changelog so a
# plain grep of this file returns the version and not a changelog line (S98).
VERSION = 'v1.1'
# v1.1 (S123): esc() no longer rewrites an apostrophe - DJ ruling B. The lossy step
#   recorded at v1.0.1 and deliberately left is now closed, and the docstring claim that
#   titles are DERIVED is true for every character. Blast radius measured, not guessed:
#   exactly one of sixteen titles carries an apostrophe, so exactly one generated block
#   changes, in Lesson_10.html. gate 51 and title_feed.to_prose() moved in the same
#   commit - leaving any one of the three behind re-creates the drift on the next apply.
# v1.0.2 (S122): THE DOCSTRING BANNER WENT STALE THE MOMENT THE HOME MOVED. The banner on
#   line 2 still read v1.0 after the previous release advanced the constant, so this file
#   carried two versions that disagreed and the FIRST one a reader meets was the wrong one.
#   Invisible to all 50 gates - book_gates does not look at instrument versions, and
#   session_versions --check passed because it reads the ANCHORED home and never the banner.
#   Caught only by grep_trap (Control D), whose entire job is to ask what a plain grep would
#   return: 1 hit, isolated to this file, 28 other artefacts silent. The banner is not a
#   second home, it is a LABEL, and a label that can go stale independently is the §5b
#   two-homes failure one file over. Both lines now carry the same string; grep_trap is the
#   check that keeps them that way.
# v1.0.1 (S121): the lossy-derivation note below - esc() rewrites an apostrophe, so one
#   emitted title is transformed rather than copied. Recorded, deliberately not fixed.
# v1.0 (S121): NEW. Generates the Bible 3.1a forward link for lessons 01-15.

LESSON_DIR = "lessons"
FIRST, LAST = 1, 16

MARK = ("<!-- ===== NEXT LESSON v1 (\u00a73.1a) \u2014 generated by next_pointer.py; "
        "do not hand-vary ===== -->")

# The §5b footer paragraph. Verified S121: matches exactly once in all sixteen.
SEAT = re.compile(r'<p class="p-c-666">\s*\n\s*<strong>LESSON ')


def esc(s):
    """Book-style entity escaping for a title pulled out of an attribute.

    DJ RULING B, S123: the APOSTROPHE branch is gone. It rewrote an ASCII apostrophe to
    &rsquo;, which made this tool's output the only curly spelling of L11's title in a
    book that spells it straight in 21 other places - and titles() html.unescape()s the
    attribute first, so the ampersand branch below is still required and the apostrophe
    branch was the only lossy one. Removing it changes exactly one character in exactly
    one file, Lesson_10.html, and makes the derivation byte-faithful as the docstring
    above has always claimed. A curly apostrophe arriving IN the strip is still honoured,
    because it now passes through untouched rather than being normalised twice.
    """
    return s.replace("&", "&amp;")


def titles(root="."):
    """Lesson titles, derived from the lesson strip rather than typed.

    The strip is byte-identical in all sixteen lessons (§6.5a), so any one of
    them is the canonical source. Asserts that identity rather than assuming it.
    """
    bodies, out = set(), {}
    for f in sorted(glob.glob(os.path.join(root, LESSON_DIR, "Lesson_*.html"))):
        s = open(f, encoding="utf-8").read()
        i = s.find('id="lesson-strip"')
        if i < 0:
            raise SystemExit(f"no lesson strip in {f}")
        blk = s[i:s.find("</div>", i)]
        bodies.add(re.sub(r"\s+", " ", blk))
        if not out:
            for m in re.finditer(r'href="Lesson_(\d+)\.html" title="([^"]*)"', blk):
                out[int(m.group(1))] = html.unescape(m.group(2))
    if len(bodies) != 1:
        raise SystemExit(f"lesson strip is NOT byte-identical ({len(bodies)} variants)")
    if sorted(out) != list(range(FIRST, LAST + 1)):
        raise SystemExit(f"strip does not name all sixteen: {sorted(out)}")
    return out


def block(n, tmap):
    """The generated block for lesson n, or None when n has no successor."""
    if n >= LAST:
        return None
    nxt = n + 1
    return (
        f"{MARK}\n"
        f'<p class="p-mt-22px" id="next-lesson">'
        f'<a href="Lesson_{nxt:02d}.html" class="link-c-2e86ab">'
        f"Next: Lesson {nxt} &mdash; {esc(tmap[nxt])} &rarr;</a></p>\n\n"
    )


def build(root="."):
    """Return {n: (path, source, expected_block)} for every lesson."""
    tmap = titles(root)
    out = {}
    for n in range(FIRST, LAST + 1):
        p = os.path.join(root, LESSON_DIR, f"Lesson_{n:02d}.html")
        out[n] = (p, open(p, encoding="utf-8").read(), block(n, tmap))
    return out


def apply_one(src, blk):
    """Insert blk at the footer seat. Returns new source."""
    m = list(SEAT.finditer(src))
    if len(m) != 1:
        raise SystemExit(f"footer seat matched {len(m)} times, expected 1")
    i = m[0].start()
    return src[:i] + blk + src[i:]


def check(root="."):
    bad = []
    for n, (p, s, blk) in build(root).items():
        have = s.count(MARK)
        if blk is None:
            if have:
                bad.append(f"L{n:02d}: carries a next-lesson block and must not")
            continue
        if have != 1:
            bad.append(f"L{n:02d}: {have} next-lesson block(s), expected 1")
        elif blk.strip() not in s:
            bad.append(f"L{n:02d}: block present but does not match the generated form")
    return bad


def write(p, s):
    """Encode first, then atomic replace (§12: a truncating open must not be reachable)."""
    data = s.encode("utf-8")
    tmp = p + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(data)
    os.replace(tmp, p)


def selftest(root="."):
    ok = True

    def rep(good, label, detail=""):
        nonlocal ok
        ok = ok and good
        print(f"   {'OK  ' if good else 'FAIL'}  {label}  {detail}")

    print(f"next_pointer.py {VERSION} \u2014 selftest")

    tmap = titles(root)
    rep(len(tmap) == 16, "titles derived from the strip, all sixteen", str(len(tmap)))
    rep(tmap[7] == "Code Organization", "a known title round-trips", repr(tmap[7]))

    rep(esc("Motors & TRIM") == "Motors &amp; TRIM", "ampersand escaped")
    rep(esc("Time Lies, Distance Doesn't") == "Time Lies, Distance Doesn't",
        "apostrophe passes through UNTRANSFORMED (DJ ruling B, S123)")

    b = block(6, tmap)
    rep('href="Lesson_07.html"' in b, "L06 points at L07")
    rep('id="next-lesson"' in b, "block carries the anchor id")
    rep("style=" not in b, "no inline style emitted (\u00a727.12)")
    rep(block(16, tmap) is None, "L16 generates no block (\u00a73.1)")

    # CONTROL A: the seat matches exactly once in every lesson, on the live tree.
    seats = {n: len(list(SEAT.finditer(s))) for n, (p, s, _) in build(root).items()}
    rep(set(seats.values()) == {1}, "footer seat unique in all sixteen", str(sorted(set(seats.values()))))

    # CONTROL B: applying to a synthetic doc puts the block BEFORE the footer.
    fake = 'x<p class="p-c-666">\n    <strong>LESSON 06</strong></p>'
    got = apply_one(fake, block(6, tmap))
    rep(got.index("next-lesson") < got.index("p-c-666"),
        "block lands ABOVE the footer, not below")

    # CONTROL C: a second apply is detectable (idempotence is NOT assumed).
    twice = apply_one(got, block(6, tmap))
    rep(twice.count(MARK) == 2, "a double-apply is visible, not silent", str(twice.count(MARK)))

    # CONTROL D: byte delta equals exactly the block length.
    rep(len(got) - len(fake) == len(block(6, tmap)),
        "byte delta == block length (\u00a76.12c)")

    # CONTROL E: a corrupted strip is rejected rather than guessed around.
    try:
        titles("/nonexistent-path-for-control-e")
        rep(False, "missing tree raises")
    except SystemExit:
        rep(True, "missing tree raises rather than returning empty")

    print("\n" + ("ALL CONTROLS PASS - loud on a double-apply and a drifted strip."
                  if ok else "SELFTEST FAILED"))
    return 0 if ok else 1


def main():
    root = "."
    if "--selftest" in sys.argv:
        return selftest(root)
    if "--apply" in sys.argv:
        n_done = 0
        for n, (p, s, blk) in build(root).items():
            if blk is None or MARK in s:
                continue
            new = apply_one(s, blk)
            assert len(new) - len(s) == len(blk), f"L{n:02d} byte delta wrong"
            write(p, new)
            n_done += 1
        print(f"applied to {n_done} lesson(s)")
        bad = check(root)
        print("VERIFY: clean" if not bad else "VERIFY FAILED:\n  " + "\n  ".join(bad))
        return 1 if bad else 0
    bad = check(root)
    if bad:
        print("\n".join(bad))
        return 1
    print("every lesson 01-15 carries its generated next-lesson block; L16 correctly has none")
    return 0


if __name__ == "__main__":
    sys.exit(main())
