#!/usr/bin/env python3
"""next_pointer.py v1.0 - the end-of-lesson forward link (Bible §3.1a).

Generates ONE byte-identical-by-construction block per lesson and seats it
immediately before the §5b footer paragraph, which is the last element on the
page and the only seat present in all sixteen lessons.

Entrypoint trap (§24 house rule): the real entrypoint is build(dir), NOT main().

Design constraints, each of them load-bearing:
  * Every class used already exists in css/book.css, so applying this does NOT
    move the stylesheet and §27.8b's three-step sequence never runs.
  * No inline style="" is emitted (§27.12).
  * The href and the id both resolve, so §27.14 stays green.
  * Lesson titles are DERIVED from the lesson strip, never typed (§24.10).
  * L16 gets no block: it is the last lesson and is entitled to none (§3.1).

Usage:
    python3 next_pointer.py --selftest
    python3 next_pointer.py --check        # exit 1 if any lesson is missing it
    python3 next_pointer.py --apply
"""

import glob
import html
import os
import re
import sys

VERSION = 'v1.0'

LESSON_DIR = "lessons"
FIRST, LAST = 1, 16

MARK = ("<!-- ===== NEXT LESSON v1 (\u00a73.1a) \u2014 generated by next_pointer.py; "
        "do not hand-vary ===== -->")

# The §5b footer paragraph. Verified S121: matches exactly once in all sixteen.
SEAT = re.compile(r'<p class="p-c-666">\s*\n\s*<strong>LESSON ')


def esc(s):
    """Book-style entity escaping for a title pulled out of an attribute."""
    s = s.replace("&", "&amp;")
    s = s.replace("'", "&rsquo;").replace("\u2019", "&rsquo;")
    return s


def titles(root="."):
    """Lesson titles, derived from the lesson strip rather than typed.

    The strip is byte-identical in all sixteen lessons (§6.5a), so any one of
    them is the canonical source. Asserts that identity rather than assuming it.
    """
    bodies, out = set(), {}
    for f in sorted(glob.glob(os.path.join(root, LESSON_DIR, "Lesson_*.html"))):
        s = open(f, encoding="utf-8").read()
        i = s.find('id="lesson-strip"')
        if i < 0:
            raise SystemExit(f"no lesson strip in {f}")
        blk = s[i:s.find("</div>", i)]
        bodies.add(re.sub(r"\s+", " ", blk))
        if not out:
            for m in re.finditer(r'href="Lesson_(\d+)\.html" title="([^"]*)"', blk):
                out[int(m.group(1))] = html.unescape(m.group(2))
    if len(bodies) != 1:
        raise SystemExit(f"lesson strip is NOT byte-identical ({len(bodies)} variants)")
    if sorted(out) != list(range(FIRST, LAST + 1)):
        raise SystemExit(f"strip does not name all sixteen: {sorted(out)}")
    return out


def block(n, tmap):
    """The generated block for lesson n, or None when n has no successor."""
    if n >= LAST:
        return None
    nxt = n + 1
    return (
        f"{MARK}\n"
        f'<p class="p-mt-22px" id="next-lesson">'
        f'<a href="Lesson_{nxt:02d}.html" class="link-c-2e86ab">'
        f"Next: Lesson {nxt} &mdash; {esc(tmap[nxt])} &rarr;</a></p>\n\n"
    )


def build(root="."):
    """Return {n: (path, source, expected_block)} for every lesson."""
    tmap = titles(root)
    out = {}
    for n in range(FIRST, LAST + 1):
        p = os.path.join(root, LESSON_DIR, f"Lesson_{n:02d}.html")
        out[n] = (p, open(p, encoding="utf-8").read(), block(n, tmap))
    return out


def apply_one(src, blk):
    """Insert blk at the footer seat. Returns new source."""
    m = list(SEAT.finditer(src))
    if len(m) != 1:
        raise SystemExit(f"footer seat matched {len(m)} times, expected 1")
    i = m[0].start()
    return src[:i] + blk + src[i:]


def check(root="."):
    bad = []
    for n, (p, s, blk) in build(root).items():
        have = s.count(MARK)
        if blk is None:
            if have:
                bad.append(f"L{n:02d}: carries a next-lesson block and must not")
            continue
        if have != 1:
            bad.append(f"L{n:02d}: {have} next-lesson block(s), expected 1")
        elif blk.strip() not in s:
            bad.append(f"L{n:02d}: block present but does not match the generated form")
    return bad


def write(p, s):
    """Encode first, then atomic replace (§12: a truncating open must not be reachable)."""
    data = s.encode("utf-8")
    tmp = p + ".tmp"
    with open(tmp, "wb") as fh:
        fh.write(data)
    os.replace(tmp, p)


def selftest(root="."):
    ok = True

    def rep(good, label, detail=""):
        nonlocal ok
        ok = ok and good
        print(f"   {'OK  ' if good else 'FAIL'}  {label}  {detail}")

    print(f"next_pointer.py {VERSION} \u2014 selftest")

    tmap = titles(root)
    rep(len(tmap) == 16, "titles derived from the strip, all sixteen", str(len(tmap)))
    rep(tmap[7] == "Code Organization", "a known title round-trips", repr(tmap[7]))

    rep(esc("Motors & TRIM") == "Motors &amp; TRIM", "ampersand escaped")
    rep(esc("Time Lies, Distance Doesn't") == "Time Lies, Distance Doesn&rsquo;t",
        "apostrophe escaped")

    b = block(6, tmap)
    rep('href="Lesson_07.html"' in b, "L06 points at L07")
    rep('id="next-lesson"' in b, "block carries the anchor id")
    rep("style=" not in b, "no inline style emitted (\u00a727.12)")
    rep(block(16, tmap) is None, "L16 generates no block (\u00a73.1)")

    # CONTROL A: the seat matches exactly once in every lesson, on the live tree.
    seats = {n: len(list(SEAT.finditer(s))) for n, (p, s, _) in build(root).items()}
    rep(set(seats.values()) == {1}, "footer seat unique in all sixteen", str(sorted(set(seats.values()))))

    # CONTROL B: applying to a synthetic doc puts the block BEFORE the footer.
    fake = 'x<p class="p-c-666">\n    <strong>LESSON 06</strong></p>'
    got = apply_one(fake, block(6, tmap))
    rep(got.index("next-lesson") < got.index("p-c-666"),
        "block lands ABOVE the footer, not below")

    # CONTROL C: a second apply is detectable (idempotence is NOT assumed).
    twice = apply_one(got, block(6, tmap))
    rep(twice.count(MARK) == 2, "a double-apply is visible, not silent", str(twice.count(MARK)))

    # CONTROL D: byte delta equals exactly the block length.
    rep(len(got) - len(fake) == len(block(6, tmap)),
        "byte delta == block length (\u00a76.12c)")

    # CONTROL E: a corrupted strip is rejected rather than guessed around.
    try:
        titles("/nonexistent-path-for-control-e")
        rep(False, "missing tree raises")
    except SystemExit:
        rep(True, "missing tree raises rather than returning empty")

    print("\n" + ("ALL CONTROLS PASS - loud on a double-apply and a drifted strip."
                  if ok else "SELFTEST FAILED"))
    return 0 if ok else 1


def main():
    root = "."
    if "--selftest" in sys.argv:
        return selftest(root)
    if "--apply" in sys.argv:
        n_done = 0
        for n, (p, s, blk) in build(root).items():
            if blk is None or MARK in s:
                continue
            new = apply_one(s, blk)
            assert len(new) - len(s) == len(blk), f"L{n:02d} byte delta wrong"
            write(p, new)
            n_done += 1
        print(f"applied to {n_done} lesson(s)")
        bad = check(root)
        print("VERIFY: clean" if not bad else "VERIFY FAILED:\n  " + "\n  ".join(bad))
        return 1 if bad else 0
    bad = check(root)
    if bad:
        print("\n".join(bad))
        return 1
    print("every lesson 01-15 carries its generated next-lesson block; L16 correctly has none")
    return 0


if __name__ == "__main__":
    sys.exit(main())
